# Florian motion plan for pose retrieval service

# The desired endeffector pose
geometry_msgs/PoseStamped  pose

# The joint group name of the appendage to be used
# "l_arm_group" and "r_arm_group" are supported currently
std_msgs/String group_name

---
uint8       OK                = 0
uint8       OCTOMAP_WARNING   = 1
uint8       IK_FAILED         = 2
uint8       PLANNER_EXCEPTION = 4
uint8       PLANNING_FAILED   = 8

trajectory_msgs/JointTrajectory trajectory
uint8                           status
